---
- name: Add RoleBinding to allow pods running under anyuid
  community.kubernetes.k8s:
    state: present
    definition:
      apiVersion: rbac.authorization.k8s.io/v1
      kind: RoleBinding
      metadata:
        name: "{{ app_ns }}:scc:anyuid"
        namespace: "{{ app_ns }}"
      roleRef:
        apiGroup: rbac.authorization.k8s.io
        kind: Role
        name: system:openshift:scc:anyuid
      subjects:
        - kind: Group
          name: system:serviceaccounts:{{ app_ns }}

- name: Create NetworkAttachmentDefinition
  community.kubernetes.k8s:
    state: present
    definition:
      apiVersion: "k8s.cni.cncf.io/v1"
      kind: NetworkAttachmentDefinition
      metadata:
        name: istio-cni
        namespace: "{{ app_ns }}"

- name: Label namespace for istio-injection
  community.kubernetes.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "{{ app_ns }}"
        labels:
          istio-injection: enabled
