---
- name: Run tnf stages
  block:
    - name: Execute cnf_cert pre-run stage
      include_tasks: pre-run.yml

    - name: Execute cnf_cert tests stage
      include_tasks: tests.yml

  always:
    - name: Execute cnf_cert teardown stage
      include_tasks: teardown.yml
...
