---
- name: Standalone containers tests
  block:
    - name: Create tmp directory for custom configurations and preflight binary
      tempfile:
        state: directory
        prefix: preflight_tmp_dir.
      register: preflight_tmp_dir

    - name: Copy registry authentication into config folder
      copy:
        src: "{{ partner_creds }}"
        dest: "{{ preflight_tmp_dir.path }}/config.json"
      when: partner_creds | length

    - name: "Run preflight check container on operator image for {{ operator.name }}"
      # introducing operator variable to reuse the functionality
      # for e2e certification when operator is defined
      vars:
        current_operator_image: "{{ c.container_image }}"
        operator:
          name: "{{ current_operator_image.split('/')[-1].split(':')[0].split('@')[0] }}"
          version: "{{ current_operator_image.split(':')[-1] }}"
          pyxis_container_identifier: "{{ c.pyxis_container_identifier | default('') }}"
          create_container_project: "{{ c.create_container_project | default('') }}"
          short_description: "{{ c.short_description | default('') }}"
          custom_project_name: "{{ c.custom_project_name | default(omit) }}"
      include_tasks: test_preflight_check_container_one_image.yml
      loop: "{{ preflight_containers_to_certify }}"
      loop_control:
        loop_var: c
  always:
    - name: Teardown
      include_tasks: teardown.yml
...