{{- if .Values.route.enabled -}}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Values.route.name }}
  labels: {{ .Values.route.labels }}
  annotations:
    {{- range $key, $value := .Values.route.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
{{- if .Values.route.path }}
  host: {{ .Values.route.path }}
{{- end }}
  port:
    {{- with (first .Values.service.ports) }}
    targetPort: {{ .name }}
    {{- end }}
  to:
    kind: Service
    name: {{ include "control-plane.fullname" . }}
{{- end }}
